/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually

  docsSidebar: [
    {
      type: "category",
      label: "Get Started",
      items: ["README", "what-is-privateai"],
    },
    {
      type: "category",
      label: "Graphs",
      items: [
        "graphs/graph-manifest",
        "graphs/what-is-knowledge-graph",
        "graphs/graphical-data-analysis",
        "graphs/graph-formation",
        "graphs/wikigraph",
        "graphs/use-cases",
      ],
    },
    {
      type: "category",
      label: "AI-powered features",
      items: [
        "ai_powered_features/integration-of-llm",
        "ai_powered_features/search-assistant",
        "ai_powered_features/recommendation-system",
        "ai_powered_features/global-search",
        "ai_powered_features/the-potential-of-openbiollm-70b",
      ],
    },
    {
      type: "category",
      label: "Privacy & Security",
      items: [
        "privacy_and_security/privacy-and-security-in-privateai",
        "privacy_and_security/fhe",
        "privacy_and_security/federated-learning",
        "privacy_and_security/additional-data-security-and-privacy-measures",
      ],
    },
    {
      type: "category",
      label: "Ecosystem",
      items: [
        "ecosystem/interaction-overview",
        "ecosystem/fsn-nodes",
        "ecosystem/psn-nodes",
        "ecosystem/initial-bonus-system-implementation",
        "ecosystem/anti-plagiarism",
        "ecosystem/privateai-pgpt",
        "ecosystem/staking",
        "ecosystem/subscription-plans",
      ],
    },
    {
      type: "category",
      label: "User Interactions and Manual",
      items: [
        "user_interactions_and_manual/user-manual",
        "user_interactions_and_manual/secure-data-management-and-access-control-in-privateai",
        "user_interactions_and_manual/like-system",
        "user_interactions_and_manual/comment-system-wireframes",
        "user_interactions_and_manual/assistant-interaction-guide",
      ],
    },
    {
      type: "category",
      label: "Public API",
      items: [
        "public_api/purpose",
        "public_api/requirements",
        "public_api/wireframes",
      ],
    },
    {
      type: "category",
      label: "Tokenomics",
      items: ["tokenomics/distribution", "tokenomics/utilities"],
    },
    {
      type: "category",
      label: "Future",
      items: [
        "future/sharing-feature",
        "future/article-access-management",
        "future/future-ecosystem",
        "future/roadmap",
      ],
    },
    {
      type: "category",
      label: "Additional information",
      items: [
        "additional_information/new-features",
        "additional_information/questions-and-answers",
        "additional_information/glossary",
      ],
    },
  ],
};

export default sidebars;
